### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by juanc37** [sdsu-its/parscore-macro#13]
I have tested the code a couple of times for bugs and have not found anything yet. Could you guys please run through a test from the master branch so we can get another set of eyes next time you happen to be in the FIT Center. We would probably be able to fully switch over to the web app after some documentation. Please comment and let me know what you see.

**Comment by tpaulus** [comment]
`clicker75` was not filtered from Bb -> Par converison. Everything else looks good.

**Comment by juanc37** [comment]
The clicker students that I have passed through it were all filtered out. could you send me an email containing the CSV that this happened with so i can test it? @tpaulus
