### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by tpaulus** [sdsu-its/parscore-macro#9]
```
app.js:70 Uncaught TypeError: Cannot read property 'replace' of undefined
    at readFileTXT (app.js:70)
    at FileReader.reader.onload (app.js:34)
readFileTXT @ app.js:70
reader.onload @ app.js:34
FileReader (async)
handleFileSelect @ app.js:37
```

**Comment by tpaulus** [comment]
Issue occurs when a user tries to upload a converted Users List. We may want to implement a catch all and show a SWAL if an error occurs.

**Comment by juanc37** [comment]
todo: ensure that you cannot convert a file back to csv w/o it going through parscore
todo: if any of the uname, fname, or lname equal eachother, Notify the user with SWAL to upload a file only from blackboard

**Comment by juanc37** [comment]
fixed issue in my branch, need to test. Please let me know if you are testing it
